# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!

#Virtualbox für DHCP
#Im ersten Abschnitt wird das Guest-OS der VM bestimmt.
Vagrant.configure(2) do |config|
  #config.ssh.username = "admin"
  #config.ssh.password = "admin"
  config.vm.define "dhcp" do |dhcp|
    dhcp.vm.box = "ubuntu/xenial64"
    dhcp.vm.hostname = "dhcp"
    dhcp.vm.network "private_network", ip:"192.168.20.5" 
    dhcp.vm.provider "virtualbox" do |vb|
      vb.memory = "512"  
    end     
    dhcp.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        #Gruppe Myadmin erstellen
        sudo groupadd myadmin
        #User erstellen
        sudo useradd admin -g myadmin -m -s /bin/bash
        sudo useradd bme -g myadmin -m -s /bin/bash
        #Password festlegen
        sudo chpasswd <<<admin:admin
        sudo chpasswd <<<bme:bme
        #DHCP Server installieren
        sudo apt-get -y install isc-dhcp-server
	#DHCP Config-File konfigurieren
        #Domainanme konfigurieren
        sudo sed -i 's/example.org/labor.local/g' /etc/dhcp/dhcpd.conf
        #DNS konfigurieren
        sudo sed -i 's/ns2.labor.local/8.8.8.8/g' /etc/dhcp/dhcpd.conf
        #DHCP Autorisierung aktiviert
        sudo sed -i 's/#authoritative/authoritative/g' /etc/dhcp/dhcpd.conf
        #DHCP Subnetz & Maske konfigurieren
        sudo sed -i '$asubnet 192.168.20.0 netmask 255.255.255.0 {' /etc/dhcp/dhcpd.conf
        #DHCP Range konfigurieren
        sudo sed -i '$arange 192.168.20.100 192.168.20.150;' /etc/dhcp/dhcpd.conf
        #DHCP Gateway konfigurieren
        sudo sed -i '$aoption routers 192.168.20.1;' /etc/dhcp/dhcpd.conf
        sudo sed -i '$a}' /etc/dhcp/dhcpd.conf
        #DHCP Server neustarten
	sudo service isc-dhcpd-server restart
        #Tastaturlayout anpassen
        sudo sed -i 's/XKBLAYOUT="us"/XKBLAYOUT="ch"/g' /etc/default/locale
        #Local Firewall installieren
        sudo apt-get -y install ufw gufw 
        sudo ufw allow from 10.0.2.2 to any port 22
        sudo ufw --force enable
SHELL
 end

#Virtualbox für FTP
#Im ersten Abschnitt wird das Guest-OS der VM bestimmt.
  config.vm.define "ftp" do |ftp|
    ftp.vm.box = "ubuntu/xenial64"
    ftp.vm.hostname = "ftp"
    ftp.vm.network "private_network", ip: "192.168.20.6"
    ftp.vm.network "forwarded_port", guest:3306, host:3306, auto_correct: true
    ftp.vm.provider "virtualbox" do |vb|
      vb.memory = "512"  
    end
    ftp.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        #FTP Server installieren
        sudo apt-get -y install pure-ftpd-common pure-ftpd
        #FTP Server konfigurieren
        sudo groupadd ftpgroup
        sudo useradd -g ftpgroup -d /dev/null -s /etc ftpuser
        sudo pure-pw useradd enesbajrami -u ftpuser -g ftpgroup -d /home/pubftp/enesbajrami -N 10
        #FTP Server neustarten
	#sudo service pure-ftpd-common pure-ftpd restart
        sudo /home/pubftp/enesbajrami restart
        #Tastaturlayout anpassen
        sudo sed -i 's/XKBLAYOUT="us"/XKBLAYOUT="ch"/g' /etc/default/locale
        #Lokale Firewall installieren
        sudo apt-get -y install ufw gufw 
        sudo ufw allow from 10.0.2.2 to any port 22
        sudo ufw --force enable
SHELL
 end        


end